@startuml
!include xdemicskin.plantuml
title School Service Startup participant xDemicTeam
actor SchoolAdmin
participant UportMobile


SchoolAdmin --> xDemicTeam: Applies to gain access to platform,(Email, WeChat etc)
xDemicTeam -> xDemicTeam: Offline verification, and Whitelists

create ClientApp 

xDemicTeam -> ClientApp: Startup ClientApp for school
ClientApp -> ClientApp : Selective Disclosure Request Created 

ClientApp -> SchoolAdmin : Contact (email etc) Show QR code containing request
SchoolAdmin -> SchoolAdmin: Downloads App from link

SchoolAdmin -> UportMobile: Scans QR code
UportMobile -> SchoolAdmin : Authorize Request?
SchoolAdmin -> UportMobile: Allow/Disallow
UportMobile -> UportMobile: Sign Selective Disclosure Response with PushToken
UportMobile -> MessagingServer: Selective Disclosure Response
MessagingServer -> ClientApp: Selective Disclosure Response
ClientApp --> SchoolAdmin: Login SchoolAdmin and Begin Startup Wizard
@enduml
