@startuml
!include xdemicskin.plantuml

actor SchoolAdmin
participant SIS
participant ClientApp
database SchoolDatabase
SchoolAdmin -> ClientApp: Import Records From SIS

alt API Import 
	ClientApp -> SIS : Pull Student Credentials
	SIS -> ClientApp : Specific Credentials Pulled
else CSV Import
	SchoolAdmin -> SIS: Downloads CSV
	SchoolAdmin -> ClientApp : Uploads CSV
end

ClientApp -> SchoolDatabase: Matches Record
SchoolDatabase -> ClientApp: Matched Records or Errors/Conflicts

ClientApp -> BadgeMicroservice : Batch Adds Student DIDs to Transcripts

alt IPFS Record 
	BadgeMicroservice -> WebOrWeb3 : Published Record to IPFS
	WebOrWeb3 -> BadgeMicroservice : Return Published URL
	create UportMobileStudent
	BadgeMicroservice -> UportMobileStudent: Send Published IPFS as Verified Claim 
else Mobile Record
	BadgeMicroservice -> UportMobileStudent : Verified Claim
end
@enduml
