@startuml
!include xdemicskin.plantuml

participant SchoolPlatform 
participant MessagingServer
participant PushServer
participant StudentMobileApp
database IPFS
actor Student

SchoolPlatform -> MessagingServer : Verifiable Credential (VC-JWT)
MessagingServer -> PushServer :  VC-JWT
PushServer -> StudentMobileApp : Pushnote VC-JWT
PushServer -> IPFS : Resolve IPFS Links
ref over PushServer, IPFS : IPFS VC Parsing Flow
StudentMobileApp -> Student : Accept Credential?
Student -> Student : Accept or Reject
ref over StudentMobileApp, Student : Accept Reject Flow


@enduml

